### ISSUE TITLE
Segfault at t3_hevel after the first elevator

### ISSUE THREAD

**Issue by hasufell** [JACoders/OpenJK#661]
This is the second time I get a segfault, but the only time it's really reproducible.

```
Program received signal SIGSEGV, Segmentation fault.
0x00007fffe2a892f7 in PM_AnimLength (index=0, anim=4294967295)
    at /var/tmp/paludis/games-engines-OpenJK-9999/work/OpenJK-9999/code/game/bg_panimate.cpp:4381
4381		return level.knownAnimFileSets[index].animations[anim].numFrames * abs(level.knownAnimFileSets[index].animations[anim].frameLerp);
(gdb) bt
#0  0x00007fffe2a892f7 in PM_AnimLength (index=0, anim=4294967295)
    at /var/tmp/paludis/games-engines-OpenJK-9999/work/OpenJK-9999/code/game/bg_panimate.cpp:4381
#1  0x00007fffe2a1b078 in NPC_ChoosePainAnimation (
    self=0x7fffe2eda440 <g_entities+628320>, other=<optimized out>, 
    point=<optimized out>, damage=<optimized out>, mod=<optimized out>, 
    hitLoc=<optimized out>, voiceEvent=1)
    at /var/tmp/paludis/games-engines-OpenJK-9999/work/OpenJK-9999/code/game/NPC_reactions.cpp:382
#2  0x00007fffe2a1b633 in NPC_Pain (self=0x7fffe2eda440 <g_entities+628320>, 
    inflictor=0x7fffe2fb6230 <g_entities+1528912>, other=<optimized out>, 
    point=0x7fffe2e90354 <g_entities+324980>, damage=1, mod=45, hitLoc=32767)
    at /var/tmp/paludis/games-engines-OpenJK-9999/work/OpenJK-9999/code/game/NPC_reactions.cpp:547
#3  0x00007fffe297f535 in NPC_ST_Pain (self=0x7fffe2eda440 <g_entities+628320>, 
    inflictor=0xffffffff, other=0x6820, point=0x7fffe2da9138 <level>, damage=1, 
    mod=2, hitLoc=<optimized out>)
    at /var/tmp/paludis/games-engines-OpenJK-9999/work/OpenJK-9999/code/game/AI_Stormtrooper.cpp:350
#4  0x00007fffe29b2fe3 in G_Damage (targ=<optimized out>, inflictor=<optimized out>, 
    attacker=<optimized out>, dir=<optimized out>, point=<optimized out>, damage=0, 
    dflags=<optimized out>, mod=45, hitLoc=<optimized out>)
    at /var/tmp/paludis/games-engines-OpenJK-9999/work/OpenJK-9999/code/game/g_combat.cpp:6807
#5  0x00007fffe29a68c2 in G_RadiusDamage (origin=0x7fffe2e90354 <g_entities+324980>, 
    attacker=0x7fffe2ea1a78 <g_entities+396440>, damage=<optimized out>, 
    radius=<optimized out>, ignore=0x7fffe2ea1a78 <g_entities+396440>, mod=45)
    at /var/tmp/paludis/games-engines-OpenJK-9999/work/OpenJK-9999/code/game/g_combat.cpp:7027
#6  0x00007fffe29caa80 in NoghriGasCloudThink (
    self=0x7fffe2e901f8 <g_entities+324632>)
    at /var/tmp/paludis/games-engines-OpenJK-9999/work/OpenJK-9999/code/game/g_missile.cpp:470
#7  0x00007fffe29bfbda in G_RunThink (ent=<optimized out>)
    at /var/tmp/paludis/games-engines-OpenJK-9999/work/OpenJK-9999/code/game/g_main.cpp:1057
#8  G_RunFrame (levelTime=<optimized out>)
    at /var/tmp/paludis/games-engines-OpenJK-9999/work/OpenJK-9999/code/game/g_main.cpp:2037
#9  0x0000000000451d7e in SV_Frame (msec=1000, fractionMsec=<optimized out>)
    at /var/tmp/paludis/games-engines-OpenJK-9999/work/OpenJK-9999/code/server/sv_main.cpp:513
#10 0x0000000000431938 in Com_Frame ()
    at /var/tmp/paludis/games-engines-OpenJK-9999/work/OpenJK-9999/code/qcommon/common.cpp:1395
#11 0x000000000049ddda in main (argc=<optimized out>, argv=<optimized out>)
    at /var/tmp/paludis/games-engines-OpenJK-9999/work/OpenJK-9999/shared/sys/sys_main.cpp:743
```

**Comment by hasufell** [comment]
with **-O2**

```
Program received signal SIGSEGV, Segmentation fault.
0x00007fffe2a8f597 in PM_AnimLength (index=0, anim=4294967295)
    at /var/tmp/paludis/games-engines-OpenJK-9999/work/OpenJK-9999/code/game/bg_panimate.cpp:4381
4381		return level.knownAnimFileSets[index].animations[anim].numFrames * abs(level.knownAnimFileSets[index].animations[anim].frameLerp);
(gdb) bt
#0  0x00007fffe2a8f597 in PM_AnimLength (index=0, anim=4294967295)
    at /var/tmp/paludis/games-engines-OpenJK-9999/work/OpenJK-9999/code/game/bg_panimate.cpp:4381
#1  0x00007fffe2a35c08 in NPC_ChoosePainAnimation (
    self=0x7fffe2eda690 <g_entities+628320>, other=<optimized out>, 
    point=<optimized out>, damage=<optimized out>, mod=<optimized out>, 
    hitLoc=<optimized out>, voiceEvent=3)
    at /var/tmp/paludis/games-engines-OpenJK-9999/work/OpenJK-9999/code/game/NPC_reactions.cpp:382
#2  0x00007fffe2a361c3 in NPC_Pain (self=0x7fffe2eda690 <g_entities+628320>, 
    inflictor=0x7fffe2fb6480 <g_entities+1528912>, other=<optimized out>, 
    point=0x7fffe2e91154 <g_entities+327972>, damage=3, mod=45, hitLoc=32767)
    at /var/tmp/paludis/games-engines-OpenJK-9999/work/OpenJK-9999/code/game/NPC_reactions.cpp:547
#3  0x00007fffe299dcb5 in NPC_ST_Pain (self=0x7fffe2eda690 <g_entities+628320>, 
    inflictor=0xffffffff, other=0x6820, point=0x7fffe2da9388 <level>, damage=3, 
    mod=2, hitLoc=<optimized out>)
    at /var/tmp/paludis/games-engines-OpenJK-9999/work/OpenJK-9999/code/game/AI_Stormtrooper.cpp:350
#4  0x00007fffe29d0ef6 in G_Damage (targ=<optimized out>, inflictor=<optimized out>, 
    attacker=<optimized out>, dir=<optimized out>, point=<optimized out>, damage=0, 
    dflags=<optimized out>, mod=45, hitLoc=<optimized out>)
    at /var/tmp/paludis/games-engines-OpenJK-9999/work/OpenJK-9999/code/game/g_combat.cpp:6807
#5  0x00007fffe29c4bc2 in G_RadiusDamage (origin=0x7fffe2e91154 <g_entities+327972>, 
    attacker=0x7fffe2ea1cc8 <g_entities+396440>, damage=<optimized out>, 
    radius=<optimized out>, ignore=0x7fffe2ea1cc8 <g_entities+396440>, mod=45)
    at /var/tmp/paludis/games-engines-OpenJK-9999/work/OpenJK-9999/code/game/g_combat.cpp:7027
#6  0x00007fffe29e8540 in NoghriGasCloudThink (
    self=0x7fffe2e90ff8 <g_entities+327624>)
    at /var/tmp/paludis/games-engines-OpenJK-9999/work/OpenJK-9999/code/game/g_missile.cpp:470
#7  0x00007fffe29dd83a in G_RunThink (ent=<optimized out>)
    at /var/tmp/paludis/games-engines-OpenJK-9999/work/OpenJK-9999/code/game/g_main.cpp:1057
#8  G_RunFrame (levelTime=<optimized out>)
    at /var/tmp/paludis/games-engines-OpenJK-9999/work/OpenJK-9999/code/game/g_main.cpp:2037
#9  0x000000000044d2fe in SV_Frame (msec=1000, fractionMsec=<optimized out>)
    at /var/tmp/paludis/games-engines-OpenJK-9999/work/OpenJK-9999/code/server/sv_main.cpp:513
#10 0x000000000042fed8 in Com_Frame ()
    at /var/tmp/paludis/games-engines-OpenJK-9999/work/OpenJK-9999/code/qcommon/common.cpp:1395
#11 0x000000000049797a in main (argc=<optimized out>, argv=<optimized out>)
    at /var/tmp/paludis/games-engines-OpenJK-9999/work/OpenJK-9999/shared/sys/sys_main.cpp:743
```

**Comment by hasufell** [comment]
With **-O0**
```
Program received signal SIGSEGV, Segmentation fault.
0x00007fffe2a044f0 in PM_AnimLength (index=0, anim=4294967295)
    at /var/tmp/paludis/games-engines-OpenJK-9999/work/OpenJK-9999/code/game/bg_panimate.cpp:4381
4381		return level.knownAnimFileSets[index].animations[anim].numFrames * abs(level.knownAnimFileSets[index].animations[anim].frameLerp);
(gdb) bt
#0  0x00007fffe2a044f0 in PM_AnimLength (index=0, anim=4294967295)
    at /var/tmp/paludis/games-engines-OpenJK-9999/work/OpenJK-9999/code/game/bg_panimate.cpp:4381
#1  0x00007fffe29851dd in NPC_ChoosePainAnimation (
    self=0x7fffe2eda490 <g_entities+628320>, 
    other=0x7fffe2ea1ac8 <g_entities+396440>, 
    point=0x7fffe2e90f54 <g_entities+327972>, damage=2, mod=45, hitLoc=0, 
    voiceEvent=-1)
    at /var/tmp/paludis/games-engines-OpenJK-9999/work/OpenJK-9999/code/game/NPC_reactions.cpp:382
#2  0x00007fffe298593a in NPC_Pain (self=0x7fffe2eda490 <g_entities+628320>, 
    inflictor=0x7fffe2fb6280 <g_entities+1528912>, 
    other=0x7fffe2ea1ac8 <g_entities+396440>, 
    point=0x7fffe2e90f54 <g_entities+327972>, damage=2, mod=45, hitLoc=0)
    at /var/tmp/paludis/games-engines-OpenJK-9999/work/OpenJK-9999/code/game/NPC_reactions.cpp:547
#3  0x00007fffe28a9dc4 in NPC_ST_Pain (self=0x7fffe2eda490 <g_entities+628320>, 
    inflictor=0x7fffe2fb6280 <g_entities+1528912>, 
    other=0x7fffe2ea1ac8 <g_entities+396440>, 
    point=0x7fffe2e90f54 <g_entities+327972>, damage=2, mod=45, hitLoc=0)
    at /var/tmp/paludis/games-engines-OpenJK-9999/work/OpenJK-9999/code/game/AI_Stormtrooper.cpp:350
#4  0x00007fffe28f49e3 in GEntity_PainFunc (self=0x7fffe2eda490 <g_entities+628320>, 
    inflictor=0x7fffe2fb6280 <g_entities+1528912>, 
    attacker=0x7fffe2ea1ac8 <g_entities+396440>, 
    point=0x7fffe2e90f54 <g_entities+327972>, damage=2, mod=45, hitLoc=0)
    at /var/tmp/paludis/games-engines-OpenJK-9999/work/OpenJK-9999/code/game/g_functions.cpp:354
#5  0x00007fffe28ef423 in G_Damage (targ=0x7fffe2eda490 <g_entities+628320>, 
    inflictor=0x7fffe2fb6280 <g_entities+1528912>, 
    attacker=0x7fffe2ea1ac8 <g_entities+396440>, dir=0x7fffffff9f1c, 
    point=0x7fffe2e90f54 <g_entities+327972>, damage=2, dflags=11, mod=45, hitLoc=0)
    at /var/tmp/paludis/games-engines-OpenJK-9999/work/OpenJK-9999/code/game/g_combat.cpp:6807
#6  0x00007fffe28de1b5 in G_RadiusDamage (origin=0x7fffe2e90f54 <g_entities+327972>, 
    attacker=0x7fffe2ea1ac8 <g_entities+396440>, damage=4, radius=100, 
    ignore=0x7fffe2ea1ac8 <g_entities+396440>, mod=45)
    at /var/tmp/paludis/games-engines-OpenJK-9999/work/OpenJK-9999/code/game/g_combat.cpp:7027
#7  0x00007fffe290f8d2 in NoghriGasCloudThink (
    self=0x7fffe2e90df8 <g_entities+327624>)
    at /var/tmp/paludis/games-engines-OpenJK-9999/work/OpenJK-9999/code/game/g_missile.cpp:470
#8  0x00007fffe28f3995 in GEntity_ThinkFunc (self=0x7fffe2e90df8 <g_entities+327624>)
    at /var/tmp/paludis/games-engines-OpenJK-9999/work/OpenJK-9999/code/game/g_functions.cpp:133
#9  0x00007fffe290099f in G_RunThink (ent=0x7fffe2e90df8 <g_entities+327624>)
    at /var/tmp/paludis/games-engines-OpenJK-9999/work/OpenJK-9999/code/game/g_main.cpp:1057
#10 0x00007fffe2900285 in G_RunFrame (levelTime=82650)
    at /var/tmp/paludis/games-engines-OpenJK-9999/work/OpenJK-9999/code/game/g_main.cpp:2037
#11 0x00000000004766c5 in SV_Frame (msec=8, fractionMsec=0)
    at /var/tmp/paludis/games-engines-OpenJK-9999/work/OpenJK-9999/code/server/sv_main.cpp:513
#12 0x000000000044b67a in Com_Frame ()
    at /var/tmp/paludis/games-engines-OpenJK-9999/work/OpenJK-9999/code/qcommon/common.cpp:1395
#13 0x00000000004c4133 in main (argc=1, argv=0x7fffffffd6c8)
    at /var/tmp/paludis/games-engines-OpenJK-9999/work/OpenJK-9999/shared/sys/sys_main.cpp:743
```

**Comment by hasufell** [comment]
Noticable is probably that there are a lot of enemies at that level and lots of fighting going on.

**Comment by ensiform** [comment]
PM_AnimLength issue is known I think?

Thought it was fixed.

**Comment by hasufell** [comment]
I'm at 38aa58182e321be9dc72778a46684c10be5d494c.

**Comment by hasufell** [comment]
The code was compiled with **clang-3.6.0**. Further investigation shows that I could not reproduce it with **gcc-4.8.4** which doesn't mean the bug is gone.

So it could be that something is relying on gcc-specific behavior.

**Comment by xycaleth** [comment]
Good find :)

The backtrace is showing that `-1` is being passed as the animation index into `PM_AnimLength`:
> #0  0x00007fffe2a044f0 in PM_AnimLength (index=0, anim=4294967295)

Might be worth seeing why it's being set to `-1`, or rather why it hasn't been changed from its default value in the code around here:
https://github.com/JACoders/OpenJK/blob/master/code/game/NPC_reactions.cpp#L382

**Comment by xycaleth** [comment]
The same issue was fixed in 26a6261 but the SP code is slightly different.

Reviewing the code again, it doesn't look like it fixes the problem in all cases. There are still some cases where `pain_anim` is never set. I'm not sure what the best solution is here because `painDebounceTime` seems to be animation-dependent here, but an animation isn't always set...

**Comment by xycaleth** [comment]
Or perhaps what would be in more useful is why the problem isn't reproducible when compiled with gcc and not clang...

**Comment by mgorny** [comment]
Looking at the code, it seems that `pain_anim` is set properly only inside the conditional branch [l334-366] (https://github.com/JACoders/OpenJK/blob/master/code/game/NPC_reactions.cpp#L334), described as 'play an anim'. There it either gets set conditionally, or randomly as a fallback, and used to play the animation.

Now, the outer code on [l382] (https://github.com/JACoders/OpenJK/blob/master/code/game/NPC_reactions.cpp#L382) seems to need to determine the length of `pain_anim`. And this fails if it isn't set to a valid value, i.e. one of the other `if` branches is run. Then an invalid value of `-1` is passed, and negative array lookup is done.

It's not really a compiler issue, rather a random memory layout issue. In other words, it segfaults because clang just happened to organize memory a bit more safely than gcc — while in gcc it reads some random junk.

Not knowing what the code is supposed to do, I can't suggest a proper solution. Maybe the `PM_AnimLength(...)` should be added only if `pain_anim` was set to a valid value, and otherwise disregarded. Maybe some other value should be added in the other cases (force-gripping, force-draining, gas).

**Comment by ensiform** [comment]
You don't by any chance have custom animations installed at all do you?

**Comment by hasufell** [comment]
I don't think so, but my copy of jka is an old one. It's not a recent steam or gog version.

**Comment by ensiform** [comment]
As long as its 1.01 it doesn't matter.

**Comment by ensiform** [comment]
JA+ etc for example install their animations in base

**Comment by carlomontec** [comment]
I am using the last available build and it happens exactly the same under OS X Mavericks :/ I have the Steam version of JA. Any ideas what could be? I deactivated all additional mods and stuff and gives the same error.
