### ISSUE TITLE
JKO: SIGSEGV when deflecting rocket with Force

### ISSUE THREAD

**Issue by Civil** [JACoders/OpenJK#778]
In Debug mode it causes SIGABRT, in Release it's SIGSEGV somewhere after.
```
Program received signal SIGABRT, Aborted.
0x00007ffff6abe528 in raise () from /lib64/libc.so.6
(gdb) backtrace
#0  0x00007ffff6abe528 in raise () from /lib64/libc.so.6
#1  0x00007ffff6abf97a in abort () from /lib64/libc.so.6
#2  0x00007ffff6ab7417 in __assert_fail_base () from /lib64/libc.so.6
#3  0x00007ffff6ab74c2 in __assert_fail () from /lib64/libc.so.6
#4  0x00007ffff0f43fed in G2API_InitGhoul2Model (ghoul2=..., fileName=0x7fffffffc030 "models/weapons2/noweap/noweap.glm", customSkin=0, customShader=0, 
    modelFlags=0, lodBias=0) at /home/civil/src/OpenJK/code/rd-vanilla/G2_API.cpp:794
#5  0x0000000000472d63 in SV_G2API_InitGhoul2Model (ghoul2=..., fileName=0x7fffffffc030 "models/weapons2/noweap/noweap.glm", modelIndex=51, customSkin=0, 
    customShader=0, modelFlags=0, lodBias=0) at /home/civil/src/OpenJK/code/server/sv_game.cpp:593
#6  0x00007fffd76c6f6b in G_CreateG2AttachedWeaponModel (ent=0x7fffd7cde0c0 <g_entities+268128>, 
    psWeaponModel=0x7fffd7fbb6b0 <weaponData+21200> "models/weapons2/noweap/noweap.md3") at /home/civil/src/OpenJK/codeJK2/game/wp_saber.cpp:295
#7  0x00007fffd75eb507 in NPC_ChangeWeapon (newWeapon=18) at /home/civil/src/OpenJK/codeJK2/game/NPC_combat.cpp:844
#8  0x00007fffd75b20ba in ATST_Attack () at /home/civil/src/OpenJK/codeJK2/game/AI_Atst.cpp:228
#9  0x00007fffd75b22f8 in NPC_BSATST_Default () at /home/civil/src/OpenJK/codeJK2/game/AI_Atst.cpp:326
#10 0x00007fffd75e3be5 in NPC_BehaviorSet_ATST (bState=0) at /home/civil/src/OpenJK/codeJK2/game/NPC.cpp:1631
#11 0x00007fffd75e3d77 in NPC_RunBehavior (team=2, bState=0) at /home/civil/src/OpenJK/codeJK2/game/NPC.cpp:1729
#12 0x00007fffd75e4100 in NPC_ExecuteBState (self=0x7fffd7cde0c0 <g_entities+268128>) at /home/civil/src/OpenJK/codeJK2/game/NPC.cpp:1874
#13 0x00007fffd75e4b7a in NPC_Think (self=0x7fffd7cde0c0 <g_entities+268128>) at /home/civil/src/OpenJK/codeJK2/game/NPC.cpp:2165
#14 0x00007fffd7665fd1 in GEntity_ThinkFunc (self=0x7fffd7cde0c0 <g_entities+268128>) at /home/civil/src/OpenJK/codeJK2/game/g_functions.cpp:70
#15 0x00007fffd767068b in G_RunThink (ent=0x7fffd7cde0c0 <g_entities+268128>) at /home/civil/src/OpenJK/codeJK2/game/g_main.cpp:977
#16 0x00007fffd76711f8 in G_RunFrame (levelTime=869350) at /home/civil/src/OpenJK/codeJK2/game/g_main.cpp:1410
#17 0x0000000000475824 in SV_Frame (msec=16, fractionMsec=0) at /home/civil/src/OpenJK/code/server/sv_main.cpp:513
#18 0x000000000044b47c in Com_Frame () at /home/civil/src/OpenJK/code/qcommon/common.cpp:1391
#19 0x00000000004c0a34 in main (argc=1, argv=0x7fffffffd828) at /home/civil/src/OpenJK/shared/sys/sys_main.cpp:789
```

**Comment by ensiform** [comment]
No clue why that would be there >.<

JKA:
```
C++
if (model==ghoul2.size())
	{
		assert(model < 8);	//arb, just catching run-away models
		CGhoul2Info info;
		strcpy(info.mFileName, fileName);
		info.mModelindex = 0;
		if(G2_TestModelPointers(&info)) {
		ghoul2.push_back(CGhoul2Info());
		} else {
			return -1;
		}
	}
```

JKO:
```
C++
if (model==ghoul2.size())
	{
		ghoul2.push_back(CGhoul2Info());
	}
```

**Comment by sudge** [comment]
@Civil have you JKO build for windows? Can you please upload it in dropbox/gdrive etc, I would like to test some. Or it's even included, I dunno.

**Comment by ensiform** [comment]
No i do not sorry.

**Comment by Civil** [comment]
@sudge I don't have appropriate build environment and any experience with windows development, sorry. If there are any step-by-step guides maybe I'll be able to follow them.

**Comment by ensiform** [comment]
https://github.com/JACoders/OpenJK/wiki/Compilation-guide
